apiVersion: v1
kind: Template
metadata:
  name: esb-fsm-tdc-nexus-cierre
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: ${PARAM_IMAGE_NAME}
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      labels:
        app: ${PARAM_APP_NAME}
      name: ${PARAM_APP_NAME}
    spec:
      selector:
        deploymentConfig: ${PARAM_APP_NAME}
      runPolicy: Serial
      source:
        type: Binary
      strategy:
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: redhat-openjdk18-openshift:1.2
            namespace: openshift
      output:
        to:
          kind: ImageStreamTag
          name: ${PARAM_IMAGE_NAME}:latest
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: ${PARAM_APP_NAME}
      name: ${PARAM_APP_NAME}
    spec:
      selector:
        deploymentConfig: ${PARAM_APP_NAME}
      template:
        metadata:
          labels:
            deploymentConfig: ${PARAM_APP_NAME}
            name: ${PARAM_APP_NAME}
            environment: dev
            tier: backend
            frecuencia: on-demand
            mensajeEntrada: rest
            critico: "si"
            protocolo: https
            asincronico: "no"
        spec:
          containers:
            - name: ${PARAM_APP_NAME}
              env:
                - name: TZ
                  value: America/Argentina/Buenos_Aires
                - name: JAVA_OPTIONS
                  value: >-
                    -Dext.properties.file=file:/opt/config/application.properties
                    -Djavax.net.ssl.trustStore=/tmp/src/classes/certs/ssocert.jks
                    -Djavax.net.ssl.trustStorePassword=edenor
                - name: SERVICE_NEXUS_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: service.nexus.password
                      name: edenor-service-nexus
                - name: SERVICE_NEXUS_USER
                  valueFrom:
                    secretKeyRef:
                      key: service.nexus.user
                      name: edenor-service-nexus
              image: ${PARAM_IMAGE_NAME}:latest
              ports:
                - containerPort: 8080
                  protocol: TCP
                - containerPort: 8081
                  protocol: TCP
              readinessProbe:
                failureThreshold: 3
                httpGet:
                  path: /actuator/health
                  port: 8081
                  scheme: HTTP
                initialDelaySeconds: 160
                periodSeconds: 90
                successThreshold: 1
                timeoutSeconds: 120
              livenessProbe:
                failureThreshold: 3
                httpGet:
                  path: /actuator/health
                  port: 8081
                  scheme: HTTP
                initialDelaySeconds: 120
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 120
              resources:
                limits:
                  cpu: 300m
                  memory: 512Mi
                requests:
                  cpu: 50m
                  memory: 512Mi
              volumeMounts:
                - mountPath: /opt/config
                  name: ${PARAM_APP_NAME}-config-vol
                - mountPath: /opt/secret/nexus
                  name: edenor-service-nexus
          volumes:
            - name: edenor-service-nexus
              secret:
                defaultMode: 420
                secretName: edenor-service-nexus
            - configMap:
                defaultMode: 420
                name: ${PARAM_APP_NAME}-config
              name: ${PARAM_APP_NAME}-config-vol
      triggers: []
      replicas: 1
      strategy:
        type: Rolling
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: ${PARAM_APP_NAME}
      name: ${PARAM_APP_NAME}
    spec:
      ports:
        - port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        deploymentConfig: ${PARAM_APP_NAME}
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        app: ${PARAM_APP_NAME}
      name: ${PARAM_APP_NAME}
    spec:
      tls:
        termination: edge
      to:
        kind: Service
        name: ${PARAM_APP_NAME}
        weight: 100
      wildcardPolicy: None
  - apiVersion: v1
    data:
      application.properties: |-
        server.port=8080
        server.contextPath=/
        cxf.path=/service
        edenor.integration.name=esb-fsm-tdc-nexus-cierre
        edenor.integration.type=ONLINE
        edenor.source.system=GC

        logging.config=classpath:logback.xml

        # the options from org.apache.camel.spring.boot.CamelConfigurationProperties can be configured here
        #Todo borrar
        camel.springboot.name=eps-rest-services

        # lets listen on all ports to ensure we can be invoked from the pod IP
        server.address=0.0.0.0
        management.address=0.0.0.0

        # lets use a different management port in case you need to listen to HTTP requests on 8080
        management.server.port=8081
        management.endpoint.health.probes.enabled=true
        management.endpoints.web.exposure.include=health,info
        management.security.enabled=false

        # disable all management enpoints except health
        endpoints.enabled = true
        endpoints.health.enabled = true



        #Nexus Api
        endpoint.nexusApi.address=https://tapp6l:8484/ws/cerrarTdC.wsdl
        endpoint.cerrarTdC.wsdlURL=wsdl/cerrarTdC.wsdl


        #Setear esta property que es utilizada en ExceptionHandler
        endpoint.clientApi.address=${endpoint.nexusApi.address}

        #----SERVICES----#

        #SSL
        disableHostnameCheck=true
        keystoreLocation=src/jks/keystore.jks
        keystorePassword=Abcd1234
        connectionTimeout=60000


        #---- Edenor Key Cloak ----#
        edenor.keycloak.enabled=true
        edenor.keycloak.connect-timeout = 5000
        edenor.keycloak.roles=FSM_EAM

        #Edenor VM
        edenor.keycloak.realm=Edenor-dev-fsm-realm
        edenor.keycloak.auth-server-url=https://sso-sso-rh.prod-apps.pro.edenor/auth

        #Login Service Geogall - Todo cambiar a url de servicio de login publicado en Openshift
        endpoint.login.address=http://login-develop-esb-fsm-dev.noprod-apps.pro.edenor/service/token

    kind: ConfigMap
    metadata:
      name: ${PARAM_APP_NAME}-config
parameters:
  - description: The application name
    displayName: Application name
    name: PARAM_APP_NAME
    value: esb-fsm-crear-tarea-eam
    required: true
  - description: The image name
    displayName: Image name
    name: PARAM_IMAGE_NAME
    value: esb-fsm-crear-tarea-eam
    required: true
